version: "3.9"

services:
  backend:
    build: backend/.
    image: eto-backend
    # enable `platform: linux/arm64/v8` if you use ARM
    #platform: linux/arm64/v8
    env_file: backend/.env
    restart: always
    networks:
      - etoapp
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/healthcheck"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 3s

  frontend:
    build: 
      context: frontend/.
      args:
        REACT_APP_FRONT_VERSION: "1.0.0"
        REACT_APP_BACKEND_URL: "http://127.0.0.1:8000"
    image: eto-frontend
    # enable `platform: linux/arm64/v8` if you use ARM
    #platform: linux/arm64/v8
    restart: always
    env_file: frontend/.env
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - etoapp
    ports:
      - "8080:80"

  db:
    image: postgres:16-alpine
    env_file: .env
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - etoapp
    healthcheck:
      test: "pg_isready --username=${POSTGRES_USER} && psql --username=${POSTGRES_USER} --list"
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  postgres_data:

networks:
  etoapp: